include config.mk
include wayland-scanner.mk

CFLAGS += -I. -DWLR_USE_UNSTABLE -std=c99

WAYLAND_PROTOCOLS=$(shell pkg-config --variable=pkgdatadir wayland-protocols)
WAYLAND_SCANNER=$(shell pkg-config --variable=wayland_scanner wayland-scanner)

PKGS = wlroots wayland-server xcb xkbcommon libinput
CFLAGS += $(foreach p,$(PKGS),$(shell pkg-config --cflags $(p)))
LDLIBS += $(foreach p,$(PKGS),$(shell pkg-config --libs $(p)))

all: dirs dwl

clean:
	rm -rf dwl *.o *-protocol.h *-protocol.c obj

install: dwl
	install -D dwl $(PREFIX)/bin/dwl

uninstall:
	rm -f $(PREFIX)/bin/dwl

.PHONY: all clean install uninstall dirs

config.h: | config.def.h
	cp config.def.h $@

dirs:
	mkdir -p obj

obj/dwl.o: config.mk wayland-scanner.mk config.h include/client.h xdg-shell-protocol.h wlr-layer-shell-unstable-v1-protocol.h idle-protocol.h

obj/wallpaper.o: config.h include/wallpaper.h

dwl: dirs xdg-shell-protocol.o wlr-layer-shell-unstable-v1-protocol.o idle-protocol.o obj/dwl.o obj/wallpaper.o
